version: '3'

services:
  postgres:
    image: postgres:15
    container_name: karius-postgres
    environment:
      POSTGRES_USER: karius_user
      POSTGRES_PASSWORD: karius_password
      POSTGRES_DB: karius_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U karius_user -d karius_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: karius-backend
    environment:
      - DATABASE_URL=postgresql://karius_user:karius_password@postgres:5432/karius_db
      - NOVITA_API_KEY=${NOVITA_API_KEY}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - PINECONE_ENVIRONMENT=${PINECONE_ENVIRONMENT}
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./data:/app/data

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: karius-frontend
    environment:
      - API_URL=http://backend:8000
    ports:
      - "8501:8501"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data: 